class Mylocation {
  final List<String> allLocations = [
    "Alor Gajah",
    "Alor Star",
    "Ampang",
    "Asajaya",
    "Ayer Hitam",
    "Ayer Itam",
    "Ayer Keroh",
    "Bachok",
    "Bagan Datuk",
    "Bagan Serai",
    "Balik Pulau",
    "Baling",
    "Bandar Baharu",
    "Bandar Permaisuri",
    "Bandaraya Melaka",
    "Bangi",
    "Bangsar",
    "Banting",
    "Barat Daya",
    "Batang Padang",
    "Batu Caves",
    "Batu Feringgi",
    "Batu Gajah",
    "Batu Kawan",
    "Batu Pahat",
    "Bau",
    "Bayan Lepas",
    "Beaufort",
    "Belaga",
    "Beluran",
    "Beluru",
    "Bentong",
    "Bera",
    "Besut",
    "Betong",
    "Bintulu",
    "Bukit Bendera",
    "Bukit Bintang",
    "Bukit Fraser",
    "Bukit Mabong",
    "Bukit Mertajam",
    "Bukit Tengah",
    "Bukit Tinggi",
    "Butterworth",
    "Cameron Highland",
    "Cheras",
    "Cherating",
    "Cyberjaya",
    "Dalat",
    "Damansara",
    "Daro",
    "Daerah Timur Laut",
    "Daerah Barat Daya",
    "Daro",
    "Daro",
    "Dungun",
    "Gombak",
    "Gua Musang",
    "Hilir Perak",
    "Hulu Langat",
    "Hulu Perak",
    "Hulu Selangor",
    "Hulu Terengganu",
    "Jasin",
    "Jelebu",
    "Jerantut",
    "Johor Bahru",
    "Julai",
    "Kampar",
    "Kangar",
    "Kanowit",
    "Kapit",
    "Keningau",
    "Kerian",
    "Ketereh",
    "Klang",
    "Kluang",
    "Kota Belud",
    "Kota Bharu",
    "Kota Kinabalu",
    "Kota Marudu",
    "Kota Samarahan",
    "Kota Setar",
    "Kota Tinggi",
    "Kuala Kangsar",
    "Kuala Krau",
    "Kuala Krai",
    "Kuala Langat",
    "Kuala Muda",
    "Kuala Nerang",
    "Kuala Nerus",
    "Kuala Pilah",
    "Kuala Selangor",
    "Kuala Terengganu",
    "Kubang Pasu",
    "Kuching",
    "Kudat",
    "Kulim",
    "Kunak",
    "Labuan",
    "Lahad Datu",
    "Langkawi",
    "Larut Matang",
    "Lawas",
    "Lembah Pantai",
    "Lenggong",
    "Limbang",
    "Lundu",
    "Machang",
    "Manjung",
    "Maradong",
    "Marang",
    "Marudi",
    "Mas Gading",
    "Melaka Tengah",
    "Meradong",
    "Mersing",
    "Miri",
    "Muallim",
    "Muadzam Shah",
    "Mukah",
    "Muar",
    "Nibong Tebal",
    "Padang Terap",
    "Padawan",
    "Papar",
    "Parit Buntar",
    "Pasir Gudang",
    "Pasir Mas",
    "Pasir Puteh",
    "Patani",
    "Pekan",
    "Pendang",
    "Penampang",
    "Perai",
    "Petaling",
    "Petaling Jaya",
    "Pokok Sena",
    "Pontian",
    "Port Dickson",
    "Puchong",
    "Putatan",
    "Putrajaya",
    "Ranau",
    "Rembau",
    "Rompin",
    "Sabak Bernam",
    "Sandakan",
    "Sarikei",
    "Saratok",
    "Sebauh",
    "Seberang Perai Selatan",
    "Seberang Perai Tengah",
    "Seberang Perai Utara",
    "Segamat",
    "Selama",
    "Selayang",
    "Semenyih",
    "Semporna",
    "Senai",
    "Sepang",
    "Seremban",
    "Setiu",
    "Sibu",
    "Simunjan",
    "Sipitang",
    "Song",
    "Sri Aman",
    "Subang",
    "Subang Jaya",
    "Sungai Buloh",
    "Sungai Petani",
    "Taiping",
    "Tambunan",
    "Tampin",
    "Tanah Merah",
    "Tangkak",
    "Tapah",
    "Tatau",
    "Teluk Intan",
    "Temerloh",
    "Tenom",
    "Timur Laut",
    "Tuaran",
    "Tumpat",
    "Ulu Perak",
    "Ulu Selangor",
    "Yan",
    "Yong Peng",
  ];
}
